spring.datasource.url=jdbc:mysql://mydb.c3a6w4ui8zue.eu-north-1.rds.amazonaws.com:3306/springbackend?useSSL=false
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.generate-ddl=true